"""迁移到标准Alembic系统

Revision ID: c1e78e615f94
Revises: 
Create Date: 2025-11-05 10:55:33.629333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e78e615f94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('equipment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('predefined_names', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_equipment_categories_id'), 'equipment_categories', ['id'], unique=False)
    op.create_table('import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作用户ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='导入文件名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAUSED', 'CANCELLED', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False, comment='导入状态'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='处理进度（百分比）'),
    sa.Column('total_rows', sa.Integer(), nullable=False, comment='总行数'),
    sa.Column('processed_rows', sa.Integer(), nullable=False, comment='已处理行数'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功导入数量'),
    sa.Column('update_count', sa.Integer(), nullable=False, comment='更新设备数量'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='错误数量'),
    sa.Column('detailed_results', sa.JSON(), nullable=True, comment='详细处理结果'),
    sa.Column('error_details', sa.JSON(), nullable=True, comment='错误详情'),
    sa.Column('overwrite_existing', sa.Boolean(), nullable=False, comment='是否覆盖已存在的设备'),
    sa.Column('batch_size', sa.Integer(), nullable=False, comment='批处理大小'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始处理时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_sessions_id'), 'import_sessions', ['id'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('accuracy_level', sa.String(length=50), nullable=False),
    sa.Column('measurement_range', sa.String(length=100), nullable=True),
    sa.Column('calibration_cycle', sa.String(length=10), nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('calibration_method', sa.String(length=50), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('verification_agency', sa.String(length=100), nullable=True),
    sa.Column('certificate_form', sa.String(length=50), nullable=True),
    sa.Column('internal_id', sa.String(length=20), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=100), nullable=True),
    sa.Column('installation_location', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('scale_value', sa.String(length=50), nullable=True),
    sa.Column('management_level', sa.String(length=20), nullable=True),
    sa.Column('original_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_change_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calibration_notes', sa.Text(), nullable=True),
    sa.Column('disposal_reason', sa.Text(), nullable=True),
    sa.Column('current_calibration_result', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('security_question', sa.String(length=200), nullable=True),
    sa.Column('security_answer_hash', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('parent_log_id', sa.Integer(), nullable=True),
    sa.Column('rollback_log_id', sa.Integer(), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['parent_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['rollback_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('calibration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('calibration_method', sa.String(length=20), nullable=False),
    sa.Column('calibration_result', sa.String(length=20), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('certificate_form', sa.String(length=50), nullable=True),
    sa.Column('verification_agency', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_rolled_back', sa.Boolean(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_by', sa.Integer(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['rolled_back_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_history_id'), 'calibration_history', ['id'], unique=False)
    op.create_table('department_user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_user_logs_id'), 'department_user_logs', ['id'], unique=False)
    op.create_table('user_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_table('user_equipment_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'equipment_name', name='uq_category_equipment')
    )
    op.create_index(op.f('ix_user_equipment_permissions_id'), 'user_equipment_permissions', ['id'], unique=False)
    op.create_table('equipment_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_certificate', sa.Boolean(), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('calibration_history_id', sa.Integer(), nullable=True),
    sa.Column('attachment_category', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calibration_history_id'], ['calibration_history.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_attachments_id'), 'equipment_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_attachments_id'), table_name='equipment_attachments')
    op.drop_table('equipment_attachments')
    op.drop_index(op.f('ix_user_equipment_permissions_id'), table_name='user_equipment_permissions')
    op.drop_table('user_equipment_permissions')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_department_user_logs_id'), table_name='department_user_logs')
    op.drop_table('department_user_logs')
    op.drop_index(op.f('ix_calibration_history_id'), table_name='calibration_history')
    op.drop_table('calibration_history')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_import_sessions_id'), table_name='import_sessions')
    op.drop_table('import_sessions')
    op.drop_index(op.f('ix_equipment_categories_id'), table_name='equipment_categories')
    op.drop_table('equipment_categories')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
